<?php

/**
 * @file
 * Contains block_search.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_search_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_search module.
    case 'help.page.block_search':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Block du moteur de recherche') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_search_theme() {
  return [
    'block_search' => [
      'variables' => [
        'var' => [],
      ],
    ],
  ];
}
