<?php

/**
 * @file
 * Contains block_profs.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_profs_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_profs module.
    case 'help.page.block_profs':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bloc des enseignants sur les pages disciplines') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_profs_theme() {
  return [
    'profs_block' => [
      'variables' => [
        'var' => [],
      ],
    ],
  ];
}
