<?php

/**
 * @file
 * Contains block_discipline_assoc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_discipline_assoc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_discipline_assoc module.
    case 'help.page.block_discipline_assoc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_discipline_assoc_theme() {
  return [
    'discipline_block' => [
      'variables' => [
        'var' => [],
      ],
    ],
  ];
}
