<?php

/**
 * @file
 * Contains block_expo.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_expo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_expo module.
    case 'help.page.block_expo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Block d\&#039;&#039;agenda liés à l\&#039;&#039;exposition') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_expo_theme() {
  return [
    'block_expo' => [
      'variables' => [
        'var' => [],
      ],
    ],
  ];
}
