<?php

/**
 * @file
 * Contains home_expositions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function home_expositions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the home_expositions module.
    case 'help.page.home_expositions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Accueil des expositions') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function home_expositions_theme() {
  return [
    'home_expositions' => [
      'variables' => [
        'var' => [],
      ],
    ],
  ];
}
