<?php

/**
 * @file
 * Contains block_collection.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function block_collection_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_collection module.
    case 'help.page.block_collection':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Bloc collection') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function block_collection_theme() {
  return [
    'block_collection' => [
      'variables' => [
        'var' => [],
      ],
    ],
  ];
}

