<?php

/**
 * @file
 * Contains menu_page_base.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function menu_page_base_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the menu_page_base module.
    case 'help.page.menu_page_base':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Menu des pages de base') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function menu_page_base_theme() {
  return [
    'menu_page_base' => [
      'variables' => [
        'var' => [],
      ],
    ],
  ];
}
